channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - flax=0.4.0
  - jax=0.2.28
  - pip=22.0.3
  - numpy=1.22.2
  - plotly=5.6.0
  - jaxlib=0.1.75
  - python=3.10.2
  - pytorch=1.10.2
  - cudatoolkit=11.6.0
